public class InterfaceExample implements EmployeeClass{

    public void doDisplay(){
        //Here over ride with logic
    }
    
     public void pay(String emp){
         //Here over ride with logic
    }
    
     public void performance(){
        //Here over ride with logic
    }
    
     public void leave(){
        //Here over ride with logic
    }
}


// Employee, leave, pay, performance - Full/Con/Part/FreeLancer