public class LeadTriggerHelper {
    
    public static void restricFieldValueChange(Map<Id, Lead> oldMap, Map<Id, Lead> newMap){
        
       /* for(Id recordId: oldMap.keySet()){
            
            if(newMap.get(recordId).AnnualRevenue != oldMap.get(recordId).AnnualRevenue){
                newMap.get(recordId).AnnualRevenue.adderror('You cannot change the annual revenue');
            }
            if(NewMap.get(recordId).FirstName != OldMap.get(recordId).FirstName ){
                NewMap.get(recordId).FirstName.addError('You cannot change the first name');
            }
            if( NewMap.get(recordId).LeadSource != OldMap.get(recordId).LeadSource){
                NewMap.get(recordId).LeadSource.addError('You cannot change the Lead Source once it is filled ');
            }
        }*/
    }

}